#!/usr/bin/env bash
#
# Summary:
#    Update all outdated packages
#
# Usage: pm-basher update
#
pushd ${BASHER_ROOT}
git pull
popd

for p in $(basher outdated); do echo "Update "$p" ..."; basher upgrade $p; done
