#!/usr/bin/env bash
#
# Summary: Display help for a command
#
# Usage: pm-basher help [--usage] <command>

set -e

command="$1"

if [ -z "$command" ]; then
  exec lasher _help pm-basher
fi

lasher _help pm-basher "$command"
